spring:
  profiles:
    active: dev
  application:
    name: commonSpring
  jmx:
    enabled: false
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
server:
  port: 8080
  devBaseUrl: http://common.spring-dev.cn/
  testBaseUrl: http://common.spring-test.cn/
  prodBaseUrl: http://common.spring.cn/
  tomcat:
    max-threads: 400
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:*Mapper.xml
  configuration:
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    lazyLoadTriggerMethods: ""
    mapUnderscoreToCamelCase: true


#####################################
##########    DEV环境    ############
#####################################
---
spring:
  profiles: dev

datasource:
  jdbcUrl: jdbc:mysql://localhost:3306/lin2?useUnicode=true
  username: root
  password: root
  maximumPoolSize: 10

redis:
  address: localhost
  port: 7036
  auth:
  persistDb: 1
  cacheDb: 2
  maxIdle: 5
  maxTotal: 10

qcloudcos:
  bucketBaseUrl: https://t.focus-img.cn

